Fix test to work with newer byte-buddy (#6029)
Fix test to work with newer byte-buddy

Unblocks byte-buddy update from 1.8.3 to 1.8.12+. 1.8.12 (at 
least) requires the generated class has access to its super-interfaces,
and will otherwise fail with messages like:
java.lang.IllegalAccessError: class org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$CuMcRkYl
cannot access its superinterface org.openqa.selenium.remote.BaseAugmenterTest$MagicNumberHolder