[rust] Show a proper error message if we can't open metdata_path
If the file can't be opened due to permission issues selenium-manager
would just fail with a generic error message:
    thread 'main' (1207818) panicked at src/metadata.rs:102:60:
    called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

There is no way to find out which file failed to open. Noticed while
trying to get selenium to run inside a nono sandbox.