#9784 use `shutdown()` instead of `shutdownNow()` (#10063)
* #9784 use `shutdown()` instead of `shutdownNow()`

it waits for completion of already started tasks. Otherwise it may causes errors in those tasks, including succeeding NoClassDefFoundError.

* #9784 shutdown gracefully the executor service

Co-authored-by: Puja Jagani <puja.jagani93@gmail.com>
Co-authored-by: Diego Molina <diemol@users.noreply.github.com>