fix NPE when response status is null
I am not sure in which cases it happens, but I actually saw this error:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.openqa.selenium.remote.Response.getStatus()" is null
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:100)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:668)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:688)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:692)
        at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:507)
        at com.codeborne.selenide.drivercommands.CloseDriverCommand.quitSafely(CloseDriverCommand.java:50)
        at com.codeborne.selenide.drivercommands.CloseDriverCommand.close(CloseDriverCommand.java:35)
        at com.codeborne.selenide.impl.WebDriverInstance.dispose(WebDriverInstance.java:61)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783)
        at com.codeborne.selenide.drivercommands.DisposablesRegistry.disposeAllItems(DisposablesRegistry.java:57)
        at com.codeborne.selenide.drivercommands.DisposablesRegistry$SelenideCleanupShutdownHook.run(DisposablesRegistry.java:68)
```