Fix javascript errors
Fix "TypeError: command.getDefinition is not a function [editor.js:1091]" when clicking on a comment in treeview
 The related functions are unrelated for comments. So I moved them to the
 "command" block.

 Stacktrace:
 Editor.prototype.showReference@chrome://selenium-ide/content/editor.js:1091:9
 .selectCommand@chrome://selenium-ide/content/treeView.js:340:17
 onselect@chrome://selenium-ide/content/selenium-ide.xul:1:1
 onxblmousedown@chrome://global/content/bindings/tree.xml:1016:14

Fix "TypeError: command.isRollup is not a function [treeView.js:207]" when changing a comments text
 Make the commandAction Textbox aware of what kind of action this text belongs
 to and forward this information to updateCurrentCommand. This way the
 execution of the - for comment unrelated - functions updateSeleniumTargets
 and editor.showReference can be prevented.

 If a commandtype could not be read by setTextBox, the old default "command"
 is used.

 Stacktrace:
 updateSeleniumTargets@chrome://selenium-ide/content/treeView.js:209:5
 updateCurrentCommand@chrome://selenium-ide/content/treeView.js:369:21
 oninput@chrome://selenium-ide/content/selenium-ide.xul:1:1