#9784 use `shutdown()` instead of `shutdownNow()`
it waits for completion of already started tasks. Otherwise it may causes errors in those tasks, including succeeding NoClassDefFoundError.