Fixing NameError: global name 'options' is not defined.
if chrome_options is not None:

...
py/selenium/webdriver/chrome/webdriver.py", line 55, in __init__
   desired_capabilities.update(options.to_capabilities())
NameError: global name 'options' is not defined

Regression was introduced in 6a7bb83aaea4a69d6de03caddb81c9a7eb11c4b7