Add AttributeError handling when stopping.
Add AttributeError handling when calling Service.stop. I noticed that this issue occurs after attempting to initialize a webdriver.Chrome instance while 'chromedriver' is not in PATH.

Here is the aforementioned error:

`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

And here is the aforementioned stacktrace:

```
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fae11780a20>>
Traceback (most recent call last):
  File "/home/sean/.../lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 176, in __del__
    self.stop()
  File "/home/sean/.../lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 146, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
```

The proposed changes should not introduce any adverse effects as it will handle similarly to a situation where `self.process` does exist.