Update closure-library to revision eb26f425dbd99a70d2955d8fcc892f2fd0178acb and closure-compiler to v20150609 in order to pick up the Shadow DOM related https://github.com/google/closure-compiler/commit/4323eaa9ddf86a1c7360d5dfa9de3c6012e7fc2a Which we need for Shadow DOM support in atoms - to be submitted separately.
Removed some closure-library test files unnecessary in Selenium
(most closure-library test code was already excluded).

Made one change in selenium copy compared to closure-library
@ eb26f425dbd99a70d2955d8fcc892f2fd0178acb. It is in goog/style/style.js:42:
commented out two goog.forwardDeclare directives (which selenium doesn't need)
as they failed to compile as follows (will investigate separately):
Compiling: //javascript/firefox-driver:command-processor as build/javascript/firefox-driver/command-processor.js
/home/sevalo/dev/github/selenium/third_party/closure/goog/style/style.js:42: ERROR - Malformed goog.forwardDeclaration
goog.forwardDeclare('goog.events.BrowserEvent');
^
/home/sevalo/dev/github/selenium/third_party/closure/goog/style/style.js:43: ERROR - Malformed goog.forwardDeclaration
goog.forwardDeclare('goog.events.Event');
^
2 error(s), 0 warning(s)