don't fail the test if couldn't clear websocket listeners (because browser/websocket was already closed)
Failure example:

org.openqa.selenium.WebDriverException: java.io.IOException: Output closed
Build info: version: '4.44.0-SNAPSHOT', revision: 'Unknown'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-44-cloud-amd64', java.version: '21.0.9'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$3.send(JdkHttpClient.java:325)
	at org.openqa.selenium.remote.http.WebSocket.sendText(WebSocket.java:32)
	at org.openqa.selenium.bidi.Connection.send(Connection.java:150)
	at org.openqa.selenium.bidi.Connection.clearListeners(Connection.java:245)
	at org.openqa.selenium.bidi.BiDi.clearListeners(BiDi.java:122)
	at org.openqa.selenium.bidi.BiDi.close(BiDi.java:50)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:483)
	at org.openqa.selenium.SessionHandlingTest.callingAnyOperationAfterClosingTheLastWindowShouldThrowAnException(SessionHandlingTest.java:60)
Caused by: java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:145)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:376)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:367)
	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:555)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:192)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$3.lambda$send$1(JdkHttpClient.java:276)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$3.send(JdkHttpClient.java:315)
	at org.openqa.selenium.remote.http.WebSocket.sendText(WebSocket.java:32)
	at org.openqa.selenium.bidi.Connection.send(Connection.java:150)
	at org.openqa.selenium.bidi.Connection.clearListeners(Connection.java:245)
	at org.openqa.selenium.bidi.BiDi.clearListeners(BiDi.java:122)
	at org.openqa.selenium.bidi.BiDi.close(BiDi.java:50)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:483)
	at org.openqa.selenium.SessionHandlingTest.callingAnyOperationAfterClosingTheLastWindowShouldThrowAnException(SessionHandlingTest.java:60)