Fixed java client's implementation of NetworkConnection.
Changed java client's RemoteNetworkConnection to send just the integer
bitmask for the network connection, not the full object.
This will bring the java client in line with
 - the python client (see https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/mobile.py#L60 )
 - what the spec expects (see https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-modes )
 - and what chromedriver expects. prior to this change I saw

    [18.564][INFO]: COMMAND SetNetworkConnection {
       "parameters": {
          "type": {
             "airplaneMode": true,
             "class": "org.openqa.selenium.mobile.NetworkConnection$ConnectionType",
             "dataEnabled": false,
             "hCode": 1,
             "wifiEnabled": false
          }
       }
    }
being sent, which resulted in a RESPONSE SetNetworkConnection unknown
error: invalid connection_type error.