Disabling htmlunit test job on travis.
There is no need to run these tests until HtmlUnit is compatible with selenium 4
All tests fail with exception
ClassNotFoundException: org.openqa.selenium.interactions.internal.Locatable